apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: us-west2-docker.pkg.dev/ragz-gke-attempt-1/reddit-repo/redditapp:v3
        ports:
        - containerPort: 8000